### ISSUE TITLE
Sort By Date Added 

### ISSUE THREAD

**Issue by laura-almieda** [SecrecySupportTeam/secrecy#112]
Could you please add a new sorting option in which the files in the vault are sorted by the date added ?

**Comment by L-Henke** [comment]
This would be an interesting option. But it is more complicated than it might sound, because we would have to modify our file header to include the date when this file has been added. So this touches the whole encryption layer and we would have to maintain two different header versions. (Which could be handled by the update manager). But changes like this have to be tested thoroughly so don't expect this to happen too soon, but we might work on it.

**Comment by laura-almieda** [comment]
It would be really helpful if you could implement that

**Comment by L-Henke** [comment]
Sort by file type added with #114

**Comment by Doplgangr** [comment]
A quick gut-instinct of implementing a function like this comes to me as using the file timestamp.

Currently the encrypted files are rarely rewritten, so I suspect that we can use the file timestamp of the file header with
```
 file.lastModified() 
```
and sort it with the value returned.

Of course, it must be useful to include the file creation date in the file header at some point, but a current workaround should be possible.

**Comment by Doplgangr** [comment]
Closed by #131
