### ISSUE TITLE
Project structure 

### ISSUE THREAD

**Issue by StelianMorariu** [SecrecySupportTeam/secrecy#117]
This is an amazing project that solves many of my problems and I want to help  get it to the next level. Unfortunately, for a new comer that is not familiar with the project, the repository looks a little scary  and it's kind of hard to get the status of the project and where it's currently going.

The following proposition is based on my personal experience and style of working and I do not claim it's perfect or anything like that- I just want to throw it out here.

**Modules**
One of the problems this app has solved for me is the *encryption/decryption* of files and I think this  alone would be valuable as a stand-alone library.  Because this functionality is mixed in the code of the actual app it makes it really hard for new contributors to figure out the flow of the app. This could discourage some of us and also make it really hard  to maintain/extend the app.

I propose to use a **modular approach** when it comes to Secrecy, and here is the structure I would use.

 **Secrecy**
	 - app
	 - libraries
	 - modules

**app** will contain only code related to the actual app (like activities and fragments)

*com.doplgangr.secrecy*

 - activities
 - fragments
 - adapters
 - services
 - utils

**libraries** will contain 3rd party libraries that are not available on Maven or JCenter

**modules** will contain specific libraries used by the app that can be focused around an area of functionality. This decoupling serves to ease development and maintenance.

One example of a module could be *cryptography* . This module would contain all the code related to encrypting and decrypting  files. Ideally, every module developed should expose an API that is easy to use and understand and hide all the complicated stuff.

> Written with [StackEdit](https://stackedit.io/).

**Comment by L-Henke** [comment]
I joined the project last fall and I didn't find it too unintuitive, but I also needed a couple of weeks to fully understand everything. (But that applies to almost every software project). There are some workarounds in the app which might have be introduced due to the usage of android annotations, which has just been coded out. I have focused the last couple of month on improving the current code, without refactoring too much. One reason was android annotations, which might have been handy when @Doplgangr started coding, but now it was pretty annoying. Since we have this out of the code, we can start refactoring stuff.

In general, a modularized approach is a good thing, but I currently don't see much parts that should be a module. Especially not the cryptography part, because that is _the_ core functionality of Secrecy. It's purpose is to encrypt and decrypt files. I also don't think that we should make a library from the cryptography part, because there are many many crypto libraries out there and I don't think that we could generalize our crypto part into a library (or are doing anything better that somebody else).

But there are several possible features which could be realized as a module. Someone asked if we could add a text editor (for taking notes) into the app. That would make a perfect module. Also the gallery function and update manager might be excluded as a module. 

"Ideally, every module developed should expose an API that is easy to use and understand and hide all the complicated stuff." You wouldn't need a module for that. Java packages are doing pretty much the same. e.g. the ```encryption``` package exposes the ```Crypter``` interface with only 6 methods that are relevant for the outside.

In general I would suggest to get rid of the currently most annoying bugs and improve some concepts and then concentrate on a complete refactorization of the app. If you want to realize a modules, you have to have some pretty solid APIs for that. Creating these APIs while fixing general deficiency might be a little to much at the same time.

Nevertheless, we would like to see concrete proposals for a redesign.

**Comment by StelianMorariu** [comment]
Sure, I could create something more concrete to help you understand what I imagined. I would have liked to include the PRs that  have bug fixes because what I'm proposing is a huge  refactoring.

**Comment by Doplgangr** [comment]
A refactoring would be most welcome, since my project started with quite a mess with things fixed here and there, and as a nice Open Source project we should most probably follow conventions.

**Comment by StelianMorariu** [comment]
Closed by #120
