### ISSUE TITLE
Hide buttons in view mode

### ISSUE THREAD

**Issue by lenisko** [SecrecySupportTeam/secrecy#135]
Just one simply thing is missing, auto-hide on-screen buttons when entering view mode. They are annoying.

**Comment by L-Henke** [comment]
One of the things you don't notice with hardware buttons. Implemented with #136

**Comment by lenisko** [comment]
That's why I'm here :smile: 
btw, how often do you compile new application? or there is somewhere any info page how should I compile it myself?

**Comment by L-Henke** [comment]
We recently had some major redesigns in out code and are still optimizing things. I guess we currently don't dare to push an updated version into the play store, because not everything has been testes perfectly. But I think we should start to put new versions to GitHub more often, because then advanced users might try them out. 

Providing build instructions even for non-developers sounds like a good idea.

**Comment by lenisko** [comment]
Great, I'm willing to test it.
Good luck guys
