### ISSUE TITLE
Secrecy not importable as is in Android Studio

### ISSUE THREAD

**Issue by Graveen** [SecrecySupportTeam/secrecy#82]
Hello all,

Can somebody fix Secrecy to make it usable with actual release of Android Studio (1.0.2) ?

Actually, simply importing and running claims "Defaut Activity not found" (into Edit Configuration dialog).
Also, in example, into SettingFragment.java:
import com.doplgangr.secrecy.CustomApp_;
is throwing "Cannot resolve symbol CustomApp_" and this is identical for a lot of classes.

I don't know why the setup is so complex (crashalytics ? another 3rd ?) but as i restarted from scratch, i keep having theses issues, and i'm not enough fluent with gradle to understand what is missing.

Thank you @L-Henke / @matthewkwan / @Doplgangr !

**Comment by L-Henke** [comment]
You just have to use Gradle to build.
View->Tool Windows->Gradle
All tasks->secrecy->build

**Comment by L-Henke** [comment]
There seems to be another problem. Code generation from AndroidAnnotations somehow doesn't run. I really don't like the concept of AndroidAnnotations (generated code), although it eases the coding process.

**Comment by Graveen** [comment]
What is AndroidAnnotations used for ? 

I can't actually figure how i managed to compile my previous fork - but i have updated AndroidStudio since. I think we should make Secrecy importable easily, but i fear i had to use a bulldozer to make it compatible :(

Thank you if you can troubleshoot this :)

**Comment by L-Henke** [comment]
AndroidAnnotations tries to ease the development process for an Android app by generating code from annotations (e.g. @AfterViews, @Prefs). It provides "shortcuts" for some of the most used methods in the Android lifecycle. (there is an example at their main page: http://androidannotations.org/). All the files that are ending with an underscore are generated by AndroidAnnotations. If the generation process doesn't run before the "normal" compilation process, the required files are not available.

More than once I have thought about getting rid of AndroidAnnotations, because I would prefer "more" code that follows the standard development procedure instead of adding this dependency. 

I'm currently not sure what causes the build process to fail, but it seems to be related to the Android Studio update, because I also cannot compile older versions of Secrecy which have worked before.

**Comment by matthewkwan** [comment]
quite true.I initially tried to use android annotations because I was developing small scale project and don't want to keep things as simple as possible.Yet as the project grows there are more and more problems popping up. Essentially we cannot customize what happens inside those annotations and there were more than once where bugs relate to the way android annotations handle lifecycles.If asked I think I would vote for removing android annotations                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: L-HenkeSent: Wednesday, 28 January, 2015 10:58 PMTo: SecrecySupportTeam/secrecyReply To: SecrecySupportTeam/secrecyCc: Matthew KwanSubject: Re: [secrecy] Secrecy not importable as is in Android Studio (#82)AndroidAnnotations tries to ease the development process for an Android app by generating code from annotations (e.g. @AfterViews, @Prefs). It provides "shortcuts" for some of the most used methods in the Android lifecycle. (there is an example at their main page: http://androidannotations.org/). All the files that are ending with an underscore are generated by AndroidAnnotations. If the generation process doesn't run before the "normal" compilation process, the required files are not available.

More than once I have thought about getting rid of AndroidAnnotations, because I would prefer "more" code that follows the standard development procedure instead of adding this dependency. 

I'm currently not sure what causes the build process to fail, but it seems to be related to the Android Studio update, because I also cannot compile older versions of Secrecy which have worked before. 

—Reply to this email directly or view it on GitHub.

**Comment by L-Henke** [comment]
I guess we should try to remove it then. This is quite a lot of work, but I think further development can profit from it.

**Comment by L-Henke** [comment]
This should by fixed by @Doplgangr pull requests and #83.
