### ISSUE TITLE
"Problem setting up in-app billing. Please check your Play store"

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#84]
laura almeida reported this issue in the XDA thread. @Doplgangr can this be fixed if we update the payme library to the current version?

**Comment by Doplgangr** [comment]
There is not enough information to diagnose this problem, but it is possible that In app purchase is not supported by the copy of play store he/she is holding, either due to versioning or the location he/she is in.

I have composed a branch with updated Payme. I just made a build and sent for testing.
https://github.com/Doplgangr/secrecy/tree/UpdateIABLibrary
