### ISSUE TITLE
Excluding Secrecy from recently used apps doens't work in Android 5

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#85]
I discovered that in Android 5 (CM12) Secrecy isn't hidden from the recently used apps anymore. This means that the last viewed picture stays visible when leaving the app by the home button.

**Comment by Doplgangr** [comment]
Problem Reproduced.

This is probably due to the new function in android 5 where all apps (disregard open or not) will have their last state preserved in recents.

When I have a number of apps opened, (i.e. many apps in recents), secrecy is successfully hidden

When I clear all apps from recents (i.e. recents is empty) and open secrecy and minimize it, it is retained in recents.

If another app is opened and minimized, the recents only contain the new app.

**Comment by L-Henke** [comment]
This seems to be a bug in Android 5. We can only prevent Android to take a screenshot of the app for the recent list, which has been done with: 1795fca3c1f0adf500a5abb8e1f7c9fa378023e1
