### ISSUE TITLE
File decryption fails when device is rotated during decryption

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#93]
Found in this Google Play comment: https://play.google.com/store/apps/details?id=com.doplgangr.secrecy&reviewId=Z3A6QU9xcFRPRnRiTmEtN0ItY2J6RTRRQ2dSVFdEMjQ2TlRkOFZKOUVQWDQ3ZHczaHZXS0xmUUFZQ1dPQzM1NWZoSDVrSWhFWmJBV256MERQelY3eFEzZWlJ

I can reproduce the problem.

**Comment by Doplgangr** [comment]
This could be due to that the decryption function is somehow bound inside an activity, and any configuration change in the activity can trigger a remodeling of the activity instance and kill the decryption. One possible way is to put it in a job and make it independent of the activity.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: L-HenkeSent: Monday, 16 February, 2015 7:05 AMTo: SecrecySupportTeam/secrecyReply To: SecrecySupportTeam/secrecySubject: [secrecy] File decryption fails when device is rotated during decryption (#93)Found in this Google Play comment: https://play.google.com/store/apps/details?id=com.doplgangr.secrecy&reviewId=Z3A6QU9xcFRPRnRiTmEtN0ItY2J6RTRRQ2dSVFdEMjQ2TlRkOFZKOUVQWDQ3ZHczaHZXS0xmUUFZQ1dPQzM1NWZoSDVrSWhFWmJBV256MERQelY3eFEzZWlJ

I can reproduce the problem. 

—Reply to this email directly or view it on GitHub.

**Comment by Doplgangr** [comment]
closed wth #103. View implementation is just unrelated minor problem.
