### ISSUE TITLE
Cannot access external SD card in Android 5

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#94]
https://play.google.com/store/apps/details?id=com.doplgangr.secrecy&reviewId=Z3A6QU9xcFRPRTM1ZmFQM0pfME9RN0hqMHNfQkZOV0lrUVlSaXVJMzBkS0x0Y1NXelFNQmtZaHZJRDdzUlpXWTR3YWNNalRGRncyZ1RhOWs3SzR6UlFHZUNj

This guy reported, that he is unable to access his external SD card on his Galaxy S5 with Android 5. Since I don't have a device with an external SD card, I'll try to reproduce the problem in the emulator.

**Comment by Doplgangr** [comment]
There has long been a problem dealing with SD cards owing to the extremely messy external sd system‎ from Samsung that has grown to be now device dependent.It is probably better to redo the external so discovery mechanism.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: L-Henke‎Sent: Monday, 16 February, 2015 7:08 AMTo: SecrecySupportTeam/secrecyReply To: SecrecySupportTeam/secrecySubject: [secrecy] Cannot access external SD card in Android 5 (#94)https://play.google.com/store/apps/details?id=com.doplgangr.secrecy&reviewId=Z3A6QU9xcFRPRTM1ZmFQM0pfME9RN0hqMHNfQkZOV0lrUVlSaXVJMzBkS0x0Y1NXelFNQmtZaHZJRDdzUlpXWTR3YWNNalRGRncyZ1RhOWs3SzR6UlFHZUNj

This guy reported, that he is unable to access his external SD card on his Galaxy S5 with Android 5. Since I don't have a device with an external SD card, I'll try to reproduce the problem in the emulator. 

—Reply to this email directly or view it on GitHub.

**Comment by L-Henke** [comment]
I'll look if we can use the newly introduced intent ```ACTION_OPEN_DOCUMENT_TREE``` on Android 5 devices.
